import type { UnitDefinition } from '../types'

export const UNITS: UnitDefinition[] = [
  {
    id: 'scout_drone',
    name: 'Scout Drone',
    faction: 'machines',
    tier: 1,
    hp: 120,
    dmg: 45,
    speed: 'Fast',
    speedPx: 90,
    cost: 50,
    tokenColor: '#93C5FD',
    starter: true,
  },
  {
    id: 'assault_bot',
    name: 'Assault Bot',
    faction: 'machines',
    tier: 2,
    hp: 280,
    dmg: 90,
    speed: 'Medium',
    speedPx: 60,
    cost: 120,
    tokenColor: '#60A5FA',
    starter: false,
  },
  {
    id: 'vine_crawler',
    name: 'Vine Crawler',
    faction: 'plants',
    tier: 1,
    hp: 100,
    dmg: 40,
    speed: 'Fast',
    speedPx: 100,
    cost: 50,
    tokenColor: '#86EFAC',
    starter: true,
  },
  {
    id: 'thorn_beast',
    name: 'Thorn Beast',
    faction: 'plants',
    tier: 2,
    hp: 260,
    dmg: 95,
    speed: 'Medium',
    speedPx: 55,
    cost: 120,
    tokenColor: '#4ADE80',
    starter: false,
  },
  {
    id: 'apprentice_mage',
    name: 'Apprentice Mage',
    faction: 'wizards',
    tier: 1,
    hp: 90,
    dmg: 55,
    speed: 'Medium',
    speedPx: 80,
    cost: 50,
    tokenColor: '#D8B4FE',
    starter: false,
  },
  {
    id: 'elementalist',
    name: 'Elementalist',
    faction: 'wizards',
    tier: 2,
    hp: 240,
    dmg: 105,
    speed: 'Medium',
    speedPx: 58,
    cost: 120,
    tokenColor: '#C084FC',
    starter: false,
  },
]

export const UNIT_FACTION: Record<string, string> = Object.fromEntries(
  UNITS.map((u) => [u.id, u.faction])
)
