import type { UnitDefinition } from '../types'

export const UNITS: UnitDefinition[] = [
  {
    id: 'scout_drone',
    name: 'Scout Drone',
    faction: 'machines',
    tier: 1,
    hp: 80,
    dmg: 12,
    speed: 'Fast',
    speedPx: 120,
    cost: 50,
    tokenColor: '#93C5FD',
    starter: true,
  },
  {
    id: 'assault_bot',
    name: 'Assault Bot',
    faction: 'machines',
    tier: 2,
    hp: 200,
    dmg: 28,
    speed: 'Medium',
    speedPx: 80,
    cost: 120,
    tokenColor: '#60A5FA',
    starter: false,
  },
  {
    id: 'vine_crawler',
    name: 'Vine Crawler',
    faction: 'plants',
    tier: 1,
    hp: 100,
    dmg: 10,
    speed: 'Fast',
    speedPx: 120,
    cost: 50,
    tokenColor: '#86EFAC',
    starter: true,
  },
  {
    id: 'thorn_beast',
    name: 'Thorn Beast',
    faction: 'plants',
    tier: 2,
    hp: 280,
    dmg: 20,
    speed: 'Medium',
    speedPx: 80,
    cost: 120,
    tokenColor: '#4ADE80',
    starter: false,
  },
  {
    id: 'apprentice_mage',
    name: 'Apprentice Mage',
    faction: 'wizards',
    tier: 1,
    hp: 70,
    dmg: 15,
    speed: 'Medium',
    speedPx: 80,
    cost: 50,
    tokenColor: '#D8B4FE',
    starter: false,
  },
  {
    id: 'elementalist',
    name: 'Elementalist',
    faction: 'wizards',
    tier: 2,
    hp: 160,
    dmg: 30,
    speed: 'Slow',
    speedPx: 50,
    cost: 120,
    tokenColor: '#C084FC',
    starter: false,
  },
]

export const UNIT_FACTION: Record<string, string> = Object.fromEntries(
  UNITS.map((u) => [u.id, u.faction])
)
